[phases.setup]
nixPkgs = ["...", "php83", "php83Extensions.bcmath", "php83Extensions.pdo", "php83Extensions.pdo_mysql"]

[phases.build]
cmds = ["chmod +x build.sh && ./build.sh"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
